/// This class is generated by library package, I18nTranslator
   

          
Map<String, String> frValues = {
              "Flutter Demo Home Page": "Flutter Demo Page d'accueil",
                "You have pushed the button this many times:": "Vous avez appuyé sur le bouton autant de fois:",
        };
      
Map<String, String> esValues = {
              "Flutter Demo Home Page": "Página de inicio de demostración de Flutter",
                "You have pushed the button this many times:": "Has presionado el botón varias veces:",
        };
      
Map<String, String> deValues = {
              "Flutter Demo Home Page": "Flutter Demo Home Page",
                "You have pushed the button this many times:": "Sie haben den Knopf so oft gedrückt:",
        };
      
Map<String, String> zhValues = {
              "Flutter Demo Home Page": "Flutter演示首頁",
                "You have pushed the button this many times:": "您已多次按下按鈕：",
        };
      
Map<String, String> ruValues = {
              "Flutter Demo Home Page": "Домашняя страница демоверсии Flutter",
                "You have pushed the button this many times:": "Вы нажимали кнопку много раз:",
        };
      
Map<String, String> heValues = {
              "Flutter Demo Home Page": "דף הבית של הדגמנת רפרוף",
                "You have pushed the button this many times:": "לחצת על הכפתור פעמים רבות:",
        };
      
Map<String, String> faValues = {
              "Flutter Demo Home Page": "صفحه اصلی نسخه ی نمایشی Flutter",
                "You have pushed the button this many times:": "بارها این دکمه را فشار داده اید:",
        };
    
Map<String, Map<String, String>> i10nWords = {
            "fr": frValues,
              "es": esValues,
              "de": deValues,
              "zh": zhValues,
              "ru": ruValues,
              "he": heValues,
              "fa": faValues,
      };